version: '3.7'


services:
    user_service:
      image: gitlab.udevs.io:5050/safia/video_task:test
      restart: always
      environment:
        - HTTP_PORT=:8000
        - POSTGRES_HOST=postgres
        - POSTGRES_PORT=5432
        - POSTGRES_DATABASE=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
              - "8000:8000"


    postgres:
      image: "postgres"
      restart: always
      volumes:
        - voxe_psqldata:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres

volumes:
        voxe_psqldata:
